### PR TITLE
Remove prefix for RFC (??) & Improve docs

### PR DESCRIPTION
**Pull request by xxchan**
Search from RFC index, instead of CanIUse index.

### CODE REVIEW

**Comment by Folyd** [comment]
Thanks, @xxchan. We have a `:rfc` command to search RFC already, I prefer to remove the `??` sigil since too many sigils are hard for users to remember. RFC is a low-frequency search, the `:rfc` command is enough. What do you think?

**Comment by xxchan** [comment]
@Folyd Fair enough. I found `:rfc` is more powerful, e.g., it can also search for RFC number. But I think the doc isn't accessible enough for users to find this feature..

First, it's under the "Commands system" section. The difference between prefix and command seems unclear. Second, it says `:rfc` - _Show all_ Rust RFC list -- I didn't even know I could search at all 🤣

**Comment by Folyd** [comment]
Yes, commands also support search via keywords. The docs are outdated, do you mind fixing it BTW? 😅 

> The difference between prefix and command seems unclear. 

Normally, the sigil is suitable for high-frequency search, otherwise, let's make it a command.

**Comment by xxchan** [comment]
.. And I also felt confused how to see the full list since there's only a few rows. Now I just came across the paging feature while browsing the doc. I think it can be put to a more noticable place instead of the end of the doc 🤣

**Comment by xxchan** [comment]
Yes I can help improve the docs

**Comment by xxchan** [comment]
Another thing is that the doc itself is a little bit hard to find too. I was always trying looking for a doc button at the upper-right corner, and couldn't notice the "explore more" at the bottom and didn't know I can scroll down the page..

**Comment by Folyd** [comment]
> .. And I also felt confused how to see the full list since there's only a few rows. Now I just came across the paging feature while browsing the doc. I think it can be put to a more noticable place instead of the end of the doc 🤣


image

I thought I tried my best to tell the user how to use the extension, but the reality is (😅):

**Comment by Folyd** [comment]
> Yes I can help improve the docs

That would be great. Thanks ❤️

**Comment by Folyd** [comment]
> Another thing is that the doc itself is a little bit hard to find too. I was always trying looking for a doc button at the upper-right corner, and couldn't notice the "explore more" at the bottom and didn't know I can scroll down the page..

Any idea on how to improve it?

**Comment by xxchan** [comment]
For the pagination hint, is it possible to put it at the lower-right corner?
image

**Comment by xxchan** [comment]
> > Another thing is that the doc itself is a little bit hard to find too. I was always trying looking for a doc button at the upper-right corner, and couldn't notice the "explore more" at the bottom and didn't know I can scroll down the page..
> 
> Any idea on how to improve it?

Some possible ideas:
- Add some animation for the "Explore More" button
- Add an additional Docs button at the upper-right corner. It either goes to another page, or functions the same as "Explore More".

**Comment by Folyd** [comment]
> For the pagination hint, is it possible to put it at the lower-right corner? image

Yes, it's possible. I'll give it a try.

**Comment by Folyd** [comment]
> > > Another thing is that the doc itself is a little bit hard to find too. I was always trying looking for a doc button at the upper-right corner, and couldn't notice the "explore more" at the bottom and didn't know I can scroll down the page..
> > 
> > 
> > Any idea on how to improve it?
> 
> Some possible ideas:
> 
> * Add some animation for the "Explore More" button
> * Add an additional Docs button at the upper-right corner. It either goes to another page, or functions the same as "Explore More".

Good idea. 👍

**Review by Folyd — CHANGES_REQUESTED** [review]
LGTM, thanks. However, `extension/search/rfc.js` should be deleted.

**Pull request merged**
