### PR TITLE
Fix crate indexing by upgrading item types for old crate doc

### LINKED ISSUE #272: Indexing is broken in the latest version
When I do `rs @some_indexed_crate query` the search works fine, but the search results are all broken URLs.

Screenshot examples for query `rs @teloxide Update` (ALL suggested urls are broken):

A correct result would be:

Extension version: 1.13.0
Browser: firefox 122.0.1

### PR DESCRIPTION
**Pull request by yescallop**
Closes #272. Tested to work with the latest stable `std` doc, `tokio 1.36.0` (using new item types) and `teloxide 0.12.2` (using old item types).

The `itemTypes` array was reordered in rust-lang/rust@28f17d97a, which is between rust-lang/rust@2f8d81f9d (nightly-2023-11-21) and rust-lang/rust@1e9dda77b (nightly-2023-11-22). This patch makes the `sendSearchIndex` function check the `rustdoc-version` rustdoc meta variable and mark the index items when the version date is before 2023-11-22, instructing the `buildIndex` method of `DocSearch` to upgrade the item types for docs.rs documentation built before 2023-11-22.

I also removed the code for special precedence for primitive and keyword pages because it is not needed anymore with the new `itemTypes` array (explained in the commit message of rust-lang/rust@28f17d97a).

For the patch to take effect on an already indexed crate, one should remove it from the index and then add it back.

### CODE REVIEW

**Comment by Folyd** [comment]
Thanks for working on this, I'll check this this weekend.

**Review by Folyd — APPROVED** [review]
LGTM, thanks

**Comment by WaffleLapkin** [comment]
@Folyd are there any plans to make a new release with this change?

**Comment by hisriver** [comment]
Hi，@WaffleLapkin, I'll release the new version this weekend.

**Comment by Folyd** [comment]
I'll release Rust Search Extension v2.0 soon, this is a big version.

**Pull request merged**
